<Project Sdk="MSTest.Sdk/4.4.0">
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<!-- Do not generate or require XML documentation in tests -->
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Ulid" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\UntitledRpg.LibraryFile\UntitledRpg.LibraryFile.csproj"/>
	</ItemGroup>

</Project>
